title: Be Your Inner
email: zuritamanel@gmail.com
description: "Acompañamiento intuitivo, claridad emocional, energía y reconexión personal en Be Your Inner."
baseurl: "/Be-your-inner"
url: "https://lokitronik.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Clean URLs
permalink: /:title/

# Language settings
languages: ["es", "en"]
default_lang: "es"
