title: Be Your Inner
email: manel@beyourinner.com
description: "Acompañamiento intuitivo, claridad emocional, reconexión con la esencia y energía."


baseurl: ""


url: "https://beyourinner.com"

favicon: "/assets/images/favicon.ico"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:title/

languages: ["es", "en"]
default_lang: "es"
